apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/mananrawat/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 23 Nov 2024 02:25:17 IST
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
#    server: https://127.0.0.1:55505
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 23 Nov 2024 02:25:17 IST
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im5idFg0bnFoV0UwQktfVVNYeXRrYldyMWlyWGt0cXgtajVhTF9GU0VhNkUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiamVua2lucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjYyZmRhMDA3LTliNWEtNDkwNC1hNTg3LTNhNDAyYzhhNjQ1YyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmplbmtpbnMifQ.TQlGu6FPJXVGWeLQjh7VPDZXo62lG-3GmlKIbtlRehLQPBpyKlaQXcBQl5Mw65-aWmAUjPJax9sQjyGKWfpAeXkhuMlgaO0UwyDm9G_ZVB27ojpShiJkIgrQVQHxFQvfBhSCH1Z3ZoyV33WoHPXqRToH1MgxmMTyZ_WA7ZBx3BpDoZ-uW5huWiYHfs-ofOq1PFVaYZKM21ZRRq25f7qGJOjqDfZkc5vSqiPTSAAwh55gP0VFVVp-ID0f00p_omaRE5dfls4TXkyUT2euYca1u8JSaYUVn6wV6ENm8wEvIR-PR1CK69Z9EThXp5wYLxydinOYPo9RXQyStT42DRaOWw
- name: mini-jen
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlpxOXdtdU1EVHpwdUZVYW5PVENfNUp1ZEFvMFh2c0hVTW85UjFvTzJVSncifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im1pbmktamVuLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Im1pbmktamVuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGU5MTQwMGMtMTU3MC00NWRkLTg1OWEtODYzOTNmNzlhMWMzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6bWluaS1qZW4ifQ.Icog6SXtBFqwN_KFNuFHcD4bW-7T0zHU1DHMx4-amPmCrzhstUtsBsELHjAw_VJBzSFRuGoy3RjkTu0sDNBBKfQs_0kA7mxJlhdkfd3_3tUv7lhTiD5JpLWVFXYSq5Wq2_Ib5VzVYpYA5cdwcbgC2DZ66pkxlM1tH-Ps3qpDOj8D85nQZJ_IBJjh39wQY29rSAQH89jLTW3XVBlPlcd13ehFXnHf0mmMCe7AGvjtupaFoGBDTy8-smMAMt0zS9wGBHP72EDlgH6fOpb1uULL6Ee65HfZ4Ksic5pSLaUKVxcRZ1fRJjR7kC_SwViGniGfQonBkMuVRJhYwhak8sOGqg%
- name: minikube
  user:
    client-certificate: /Users/mananrawat/.minikube/profiles/minikube/client.crt
    client-key: /Users/mananrawat/.minikube/profiles/minikube/client.key