apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-12-14T19:36:07Z"
  name: login-service-external
  namespace: main
  resourceVersion: "416055"
  uid: afdd2d02-ff52-4196-91e1-4e18bce78329
spec:
  clusterIP: 10.105.244.203
  clusterIPs:
  - 10.105.244.203
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30413
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: login-service
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
