apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"login-service","namespace":"main"},"spec":{"ports":[{"port":8501,"protocol":"TCP","targetPort":8501}],"selector":{"app":"login-service"},"type":"NodePort"}}
  creationTimestamp: "2024-11-06T15:42:00Z"
  name: login-service
  namespace: main
  resourceVersion: "415899"
  uid: fdb1b9cc-57d6-4cfb-ac31-bfb8dac68435
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.252.163
  clusterIPs:
  - 10.99.252.163
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32396
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: login-service
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1
