apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: main  # Specify the namespace here
spec:
  selector:
    app: login-service
  ports:
  - protocol: TCP
    port: 8501       # Port exposed externally
    targetPort: 8501  # Match this with the port your application runs on
  type: NodePort      # Exposes it via a NodePort
