apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-11-06T15:58:34Z"
  name: login-service-nodeport
  namespace: main
  resourceVersion: "7237"
  uid: d0e8a947-7c07-4b64-84eb-dcd924a70b8b
spec:
  clusterIP: 10.106.150.14
  clusterIPs:
  - 10.106.150.14
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32669
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: login-service
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
