apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: main
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location /login {
          proxy_pass http://login-service-main:8501;
          return 200;
        }

        location /jenkins {
          proxy_pass http://jenkins-service-main:8080;
          return 200;
        }


      }
    }
