apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-details
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-details
  template:
    metadata:
      labels:
        app: kubernetes-details
    spec:
      containers:
      - name: kubernetes-details
        image: mannanrawat/kubernetes-details:latest
        volumeMounts:
          - mountPath: /root/.kube/
            name: kube-config
      volumes:
        - name: kube-config
          hostPath:
            path: /Users/mananrawat/.kube/config  # Path to your Minikube kubeconfig file

