apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mini-jen-role-binding
subjects:
- kind: ServiceAccount
  name: mini-jen
  namespace: default
roleRef:
  kind: ClusterRole
  name: mini-jen-role
  apiGroup: rbac.authorization.k8s.io

