apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mini-jen-role
rules:
  # Permissions for Pods and Nodes
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "watch", "list"]

  # Permissions for Deployments and ReplicaSets
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "watch", "list", "patch", "create", "delete"]

  # Permissions for Namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]

  # Permissions for Services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]

  # Permissions for ConfigMaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  # Permissions for Secrets
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

